# cotire.cmake 1.7.6 generated file
# /home/Order-Global/src/tfs_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/Order-Global/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.6")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_FLAGS_NONE "-Wall;-pipe;-fvisibility=hidden;-fno-strict-aliasing;-std=c++11;-flto")
set (COTIRE_TARGET_CONFIGURATION_TYPES "None")
set (COTIRE_TARGET_IGNORE_PATH "/home/Order-Global")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_NONE "/usr/include/mysql;/usr/include/luajit-2.1")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/Order-Global/src/otpch.cpp;/home/Order-Global/src/actions.cpp;/home/Order-Global/src/ban.cpp;/home/Order-Global/src/baseevents.cpp;/home/Order-Global/src/bed.cpp;/home/Order-Global/src/chat.cpp;/home/Order-Global/src/combat.cpp;/home/Order-Global/src/condition.cpp;/home/Order-Global/src/configmanager.cpp;/home/Order-Global/src/connection.cpp;/home/Order-Global/src/container.cpp;/home/Order-Global/src/creature.cpp;/home/Order-Global/src/creatureevent.cpp;/home/Order-Global/src/cylinder.cpp;/home/Order-Global/src/database.cpp;/home/Order-Global/src/databasemanager.cpp;/home/Order-Global/src/databasetasks.cpp;/home/Order-Global/src/depotchest.cpp;/home/Order-Global/src/depotlocker.cpp;/home/Order-Global/src/events.cpp;/home/Order-Global/src/fileloader.cpp;/home/Order-Global/src/game.cpp;/home/Order-Global/src/globalevent.cpp;/home/Order-Global/src/guild.cpp;/home/Order-Global/src/groups.cpp;/home/Order-Global/src/house.cpp;/home/Order-Global/src/housetile.cpp;/home/Order-Global/src/inbox.cpp;/home/Order-Global/src/ioguild.cpp;/home/Order-Global/src/iologindata.cpp;/home/Order-Global/src/iomap.cpp;/home/Order-Global/src/iomapserialize.cpp;/home/Order-Global/src/item.cpp;/home/Order-Global/src/items.cpp;/home/Order-Global/src/luascript.cpp;/home/Order-Global/src/mailbox.cpp;/home/Order-Global/src/map.cpp;/home/Order-Global/src/monster.cpp;/home/Order-Global/src/monsters.cpp;/home/Order-Global/src/mounts.cpp;/home/Order-Global/src/movement.cpp;/home/Order-Global/src/networkmessage.cpp;/home/Order-Global/src/npc.cpp;/home/Order-Global/src/otserv.cpp;/home/Order-Global/src/outfit.cpp;/home/Order-Global/src/outputmessage.cpp;/home/Order-Global/src/party.cpp;/home/Order-Global/src/player.cpp;/home/Order-Global/src/position.cpp;/home/Order-Global/src/protocol.cpp;/home/Order-Global/src/protocolgame.cpp;/home/Order-Global/src/protocollogin.cpp;/home/Order-Global/src/protocolold.cpp;/home/Order-Global/src/protocolstatus.cpp;/home/Order-Global/src/quests.cpp;/home/Order-Global/src/raids.cpp;/home/Order-Global/src/reward.cpp;/home/Order-Global/src/rewardchest.cpp;/home/Order-Global/src/rsa.cpp;/home/Order-Global/src/scheduler.cpp;/home/Order-Global/src/scriptmanager.cpp;/home/Order-Global/src/server.cpp;/home/Order-Global/src/signals.cpp;/home/Order-Global/src/script.cpp;/home/Order-Global/src/spawn.cpp;/home/Order-Global/src/spells.cpp;/home/Order-Global/src/talkaction.cpp;/home/Order-Global/src/tasks.cpp;/home/Order-Global/src/teleport.cpp;/home/Order-Global/src/thing.cpp;/home/Order-Global/src/tile.cpp;/home/Order-Global/src/iomarket.cpp;/home/Order-Global/src/tools.cpp;/home/Order-Global/src/trashholder.cpp;/home/Order-Global/src/vocation.cpp;/home/Order-Global/src/waitlist.cpp;/home/Order-Global/src/weapons.cpp;/home/Order-Global/src/viewer.cpp;/home/Order-Global/src/wildcardtree.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "7.5.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
